[package]
name = "weekend-raytracer"
version = "0.1.0"
edition = "2024"
authors = ["Aleksei Flis <fliseno1k@gmail.com>"]

[dependencies]
image = "0.25.9"
rand = "0.9.2"
rayon = "1.11.0"
ultraviolet = "0.10.0"
